---
label: Machine Learning
hide_body: false
fields:
- name: image
  type: file
  config:
    maxSize: 64
  label: image
- name: date
  type: datetime
  label: date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
pages:
- _config.yml /_posts/2020-09-17-Machine Learning.md
